In [17]:
import tensorflow as tf
import numpy as np

# Membuat sebuah tensor dengan shape (5,5) yang isinya nilai random dan disimpan di variabel random_tensor

In [18]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)

In [19]:
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)>

# Membuat sebuah tensor dengan shape ukuran (5,5) dari list nilai bilangan prima yang disimpan di varibale prime_tensor
- saya menggunakan float 32 agar pada saat penjumlahan bisa dilakukan, karena kalau menggunakan int64 tidak bisa

In [20]:
List_Prima = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(List_Prima, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

# Menampilkan dimensi dari variabel random tensor dan prime tensor

In [26]:
print("Dimensi untuk random tensor",random_tensor.get_shape())
print("Dimensi untuk bilangan prima",prime_tensor.get_shape())

Dimensi untuk random tensor (5, 5)
Dimensi untuk bilangan prima (5, 5)


# Menampilkan perhituangan aritmatika 2 variabel tersebut
- Penjumlahan
- Pengurangan
- Perkalian
- Pembagian
- Perpangkatan
- Logaritma

Penjumlahan

In [27]:
print(tf.add(random_tensor,prime_tensor))

tf.Tensor(
[[ 1.7156615  3.8922832  5.898345   7.7163982 11.349695 ]
 [12.620392  17.01532   19.274237  20.785099  28.914854 ]
 [32.01132   37.661663  42.383324  42.59535   47.86143  ]
 [52.8741    57.581387  63.029507  67.153046  71.13658  ]
 [72.50213   79.38847   82.57553   89.46214   96.45557  ]], shape=(5, 5), dtype=float32)


Pengurangan

In [28]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.2843385  -2.1077168  -4.101655   -6.2836018 -10.650305 ]
 [-13.379608  -16.98468   -18.725763  -25.214901  -29.085146 ]
 [-29.988682  -36.338337  -39.616676  -43.40465   -46.13857  ]
 [-53.1259    -60.418613  -58.970493  -66.846954  -70.86342  ]
 [-73.49787   -78.61153   -83.42447   -88.53786   -97.54443  ]], shape=(5, 5), dtype=float32)


Perkalian

In [29]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.253949     9.697533  ]
 [-36.344616    30.689228   -35.231133    41.130688   -52.809887  ]], shape=(5, 5), dtype=float32)


Pembagian

In [30]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[-0.14216927  0.29742774  0.17966902  0.10234259  0.03179044]
 [-0.02920059  0.00090116  0.01443354 -0.09630004 -0.00293608]
 [ 0.03262317  0.01788277  0.03373959 -0.00941051  0.0183283 ]
 [-0.00237547 -0.02404432  0.03327061  0.00228424  0.00192373]
 [-0.00682016  0.00491736 -0.00511411  0.00519261 -0.0056127 ]], shape=(5, 5), dtype=float32)


Perpangkatan

In [31]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 8.08484033e-02  7.10408509e-01  5.85081041e-01  9.68458578e-02
   9.56272288e-06]
 [-3.39902863e-06  1.41026244e-31  2.11057803e-11 -8.77302160e+07
  -9.43614219e-32]
 [ 1.41749847e+00  2.30968737e-07  5.99607312e+05 -1.27207896e-17
   9.02270083e-04]
 [-0.00000000e+00 -9.12027648e+08  5.63415762e+18  0.00000000e+00
   0.00000000e+00]
 [-7.75453741e-23  3.62536196e-33 -1.29249318e-31  1.46238155e-30
  -2.43510900e-26]], shape=(5, 5), dtype=float32)


Logaritma

In [32]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[        nan -0.1139717  -0.10720097 -0.33351925 -1.0506945 ]
 [        nan -4.1786094  -1.2937618          nan         nan]
 [ 0.01125463 -0.41299957  0.32448855         nan -0.14916162]
 [        nan         nan  0.7077931  -1.8770298  -1.9908084 ]
 [        nan -0.94553614         nan -0.7718819          nan]], shape=(5, 5), dtype=float32)


# Menampilkan nilai Maksimal dan Minimal dari Variabel random tensor

Maksimal

In [33]:
print("input tensor:",random_tensor.numpy())
Max_Kolom = tf.argmax(random_tensor, axis=0) #Nilai Maksimal berdasarkan kolom
Max_Baris = tf.argmax(random_tensor, axis=1) #Nilai Maksimal berdasarkan baris
print("Nilai maksimal berdasarkan kolom", Max_Kolom.numpy())
print("Nilai maksimal berdasarkan baris", Max_Baris.numpy())

input tensor: [[-0.28433853  0.8922832   0.8983451   0.7163981   0.34969485]
 [-0.37960768  0.01531979  0.27423722 -2.214901   -0.08514621]
 [ 1.0113182   0.6616626   1.383323   -0.40465203  0.86142987]
 [-0.12589967 -1.418615    2.0295074   0.15304402  0.13658497]
 [-0.49787143  0.38847125 -0.4244715   0.46214256 -0.5444318 ]]
Nilai maksimal berdasarkan kolom [2 0 3 0 2]
Nilai maksimal berdasarkan baris [2 2 2 2 3]


Minimal

In [34]:
print("input tensor:",random_tensor.numpy())
Min_Kolom = tf.argmin(random_tensor, axis=0) #Nilai Minimal berdasarkan kolom
Min_Baris = tf.argmin(random_tensor, axis=1) #Nilai Minimal berdasarkan baris
print("Nilai minimal berdasarkan kolom", Min_Kolom.numpy())
print("Nilai minimal berdasarkan baris", Min_Baris.numpy())

input tensor: [[-0.28433853  0.8922832   0.8983451   0.7163981   0.34969485]
 [-0.37960768  0.01531979  0.27423722 -2.214901   -0.08514621]
 [ 1.0113182   0.6616626   1.383323   -0.40465203  0.86142987]
 [-0.12589967 -1.418615    2.0295074   0.15304402  0.13658497]
 [-0.49787143  0.38847125 -0.4244715   0.46214256 -0.5444318 ]]
Nilai minimal berdasarkan kolom [4 3 4 1 4]
Nilai minimal berdasarkan baris [0 3 3 1 4]


# Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [37]:
print("Nilai data awal :",random_tensor.shape,prime_tensor.shape)
tensor_concat = tf.concat([random_tensor,prime_tensor],axis=0)
print("Nilai setelah digabungkan:",tensor_concat)

Ukuran data awal : (10, 5) (5, 5)
Ukuran setelah digabungkan: tf.Tensor(
[[-2.8433853e-01  8.9228320e-01  8.9834511e-01  7.1639812e-01
   3.4969485e-01]
 [-3.7960768e-01  1.5319794e-02  2.7423722e-01 -2.2149010e+00
  -8.5146211e-02]
 [ 1.0113182e+00  6.6166258e-01  1.3833230e+00 -4.0465203e-01
   8.6142987e-01]
 [-1.2589967e-01 -1.4186150e+00  2.0295074e+00  1.5304402e-01
   1.3658497e-01]
 [-4.9787143e-01  3.8847125e-01 -4.2447150e-01  4.6214256e-01
  -5.4443181e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01 

In [39]:
print(tensor_concat.shape)

(15, 5)


# Menampilkan hasil sorting descending dari kedua variabel 

Variabel random_tensor

In [44]:
print("input tensor:",random_tensor.numpy())
sort_random = tf.sort(random_tensor, direction="DESCENDING")
print("tensor yang telah tersorting descending:",sort_random.numpy())


input tensor: [[-2.8433853e-01  8.9228320e-01  8.9834511e-01  7.1639812e-01
   3.4969485e-01]
 [-3.7960768e-01  1.5319794e-02  2.7423722e-01 -2.2149010e+00
  -8.5146211e-02]
 [ 1.0113182e+00  6.6166258e-01  1.3833230e+00 -4.0465203e-01
   8.6142987e-01]
 [-1.2589967e-01 -1.4186150e+00  2.0295074e+00  1.5304402e-01
   1.3658497e-01]
 [-4.9787143e-01  3.8847125e-01 -4.2447150e-01  4.6214256e-01
  -5.4443181e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]]
tensor yang telah tersorting descending: [[ 8.9834511e-01  8.9228320e-01  7.1639812e-01  3.4969485e-01
  -2.8433853e-01]
 [ 2.7423722e-01  1.5319794e-02 -8.5146211e-02 -3.7960768e-01
  

Variabel prime_tensor

In [45]:
print("input tensor:",prime_tensor.numpy())
sort_tensor = tf.sort(prime_tensor, direction="DESCENDING")
print("tensor yang telah tersorting descending :",sort_tensor.numpy())

input tensor: [[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]]
tensor yang telah tersorting descending : [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
